### ISSUE TITLE
There is a problem with the multiple date

### ISSUE THREAD

**Issue by IPlouffe** [culturecreates/tech-support-tickets#20] opened 2023-06-15 19:38 UTC
With a contributor, we tried to enter an event : 9 à 5, la comédie musicale. There should be 6 occurences. We have added them : 25 fév to 1 march and then selected Hours. The problem is that it doent keep what I am telling him. The dates in between that I have deleted are back and it took out the hour. Plus, when we publish and we look at what it shows in the frontend, it show the starting time to the firt date entered and the end time to the last date entered. Plus in the list of the envent below it say 9 am to 5 pm even if I said that the event is from 7 pm tp 10 pm.  I have screen shot but can't add it here.

Link to event in question: https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/648b42325526a70064503b39

**Comment by troughc** [comment] 2023-06-16 19:23
The multiple dates module isn't working as expected with this event.  When Isabelle tried to add times to six dates in the modulle, the times and selected dates didn't persist. However, the 6 occurrences is displayed on the Event listing page.

Event on source website: https://calendrier.gatineau.cloud/calendrier/evenement.aspx?langue=fr-ca&id_evenement=43557
Event in CMS: https://cms.footlight.io/dashboard/6308ef4a7f771f00431d939a/events/add-event/648b42325526a70064503b39

Here are 3 screenshots from the CMS:
### Event list showing 6 occurrences
<img width="1042" alt="Screenshot 2023-06-16 at 2 54 34 PM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/ec865bae-97a1-40dc-ad89-51f73f616cbd">

### Event details showing 14 occurrences


<img width="776" alt="Screenshot 2023-06-16 at 2 54 23 PM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/20cbf0a7-0ebb-4b92-a380-2379b653e7e1">

### custom dialog showing 14 occurrences and no times

<img width="788" alt="Screenshot 2023-06-16 at 2 54 54 PM" src="https://github.com/culturecreates/tech-support-tickets/assets/64489312/04428081-7d29-4583-b393-190b0a9ec985">

**Comment by saumier** [comment] 2023-06-19 15:01
@troughc You may want to speak to Abhishek about this one. He has made a related fix which I pushed to production this morning, but I was not able to reproduce the problem described in this issue. However, I  did open a new [issue](https://github.com/culturecreates/footlight-app/issues/403) about creating a row of dates (with screen recording) so I think Abhishek should fix it before we can say this issue is fixed. 

I also check the dates for events on Minimal front-end and it looks like "voir plus de dates' is always displaying 9 to 5 for everything like it is hardcoded on their side. https://toutculture.ca/event-detail/?event=647e04668b11c40064878c34

**Comment by saumier** [comment] 2023-06-22 19:32
@AbhishekPAnil The current problem that I see when looking at this event is that the custom dates widget is not displaying the correct dates. There are 6 dates but several are offset by one day:

The dates should be:
dimanche 25 février à 19h30
vendredi 1er mars à 19h30
samedi 2 mars à 19h30
dimanche 3 mars à 19h30
vendredi 8 mars à 19h30
samedi 9 mars à 19h30

**Comment by saumier** [comment] 2023-06-22 19:43
@troughc I was able to click the correct dates and save the event as draft.  @AbhishekPAnil Is still working to fix the "drag" on safari which is not working (dates skip back 1 day). But the event can be published.

**Comment by troughc** [comment] 2023-06-22 20:02
@saumier Is the "drag" issue on safari logged somewhere else? If yes, please close this issue.

Also, I let Isabelle know she can publish this event.

**Comment by saumier** [comment] 2023-06-22 20:08
The issue for "drag" to select a row of dates is documented in https://github.com/culturecreates/footlight-app/issues/403

I am closing this issue.

**Closed as completed by saumier** 2023-06-22 20:08 UTC
Labels: Tout Culture
