### ISSUE TITLE
Feature enhancement: Lieu and Organisateur (Search) fields should work with the keyboard in Edit details

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#25] opened 2023-06-22 16:35 UTC
### Maude's User story

I can navigate most fields and menus in the Event details page using the arrow on my keyboard; and then press  Enter to select.
However, I cannot do this with the fields that have the magnifying glass (Search field).
This feels odd because those are menu that I have no choice but to enter text (all the other ones i can scroll to select an option). Search fields don't display all the options in a menu so i'm forced to type. What is strange is that I cannot complete the action on my keyboard.

Improvement: 
I want to be able to use my keyboard to type, select and then enter my choice. I do not want to have to use my mouse.

**Comment by troughc** [comment] 2023-11-14 18:09
@SyamBabu-M this issue that I asked Abhishek to do an estimate for is perhaps in the same ballpark as the one we spoke about earlier today (your evening) - https://github.com/culturecreates/tech-support-tickets/issues/9 . Maybe take a look at it to see if they should be tackled together or separately.

**Comment by AbhishekPAnil** [comment] 2023-11-16 06:41
Estimate 6h
Tasks:
1.Add the logic to move between options searchable dropdowns using keyboard.
2.Use Enter key to select the option.

**Comment by troughc** [comment] 2023-12-18 21:26
Tested in Chrome:
This is close  because I can now navigate to the Search field using the 'tab' key and then enter the text. However, if I don't enter text, the dropdown menu remains open (if I don't type text and then press enter).
**Expected behaviour:** when I move on from that field, the dropdown menu should close automatically.

Tested on SAFARI
 On SAFARI this seems to work a little better - the dropdown doesn't open automatically so it is a more fluid user experience.

_Potential future enhancement to improve the UX: sometimes when you are pressing tab and it's not clear where you are in the UI. - and once you get to the description field, you have to use your mouse to get to the next field. This is, for now, a known issue. Thanks._

**Comment by saumier** [comment] 2023-12-21 13:26
@troughc Please close this issue, or add a more clear comment on what is needed for this to be closed.

**Comment by troughc** [comment] 2024-01-10 20:38
@saumier: success would be: being able to navigate into a search field, type letters and then select from the dropdown using arrow keys and then press enter to close. And then be able to continue going through the form using the keyboard.

**Comment by SyamBabu-M** [comment] 2024-01-15 12:59
@troughc I think we covered all the requirements for this ticket in [158](https://github.com/culturecreates/footlight-app/issues/158). So can we close this? Please let me know if I missed anything. Thank you.

**Comment by troughc** [comment] 2024-01-15 14:05
@SyamBabu-M yes, I will move this to the Done column. Because it is a tech support issue, I'd like it closed only after we push to production. Thanks!

**Closed as completed** 2024-01-18 07:48 UTC
Labels: Signé Laval

**Comment by troughc** [comment] 2024-01-18 17:58
@MaudeFJ we have improved navigation with the keyboard so that it now includes search fields. Thanks!

**Comment by MaudeFJ** [comment] 2024-01-18 18:04
Amazing !! Thanks


Maude Fraser

Responsable de Signé Laval  ​


450 639-3550 – poste 7
387 rue Laurier, Laval, QC H7N 2P3
  [cid:a2601b5d-a5d8-4d60-ac4c-77121b996635]

Suivez-nous sur Facebook<https://www.facebook.com/signelaval/>, Twitter<https://twitter.com/Signe_Laval>, Instagram<https://www.instagram.com/> et Youtube<https://www.youtube.com/channel/UCR8T8HTc83UHH7CPhxTlxXw?view_as=subscriber>.





________________________________
De : troughc ***@***.***>
Envoyé : 18 janvier 2024 12:58
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Feature enhancement: Lieu and Organisateur (Search) fields should work with the keyboard in Edit details (Issue #25)


@MaudeFJ<https://github.com/MaudeFJ> we have improved navigation with the keyboard so that it now includes search fields. Thanks!
