### ISSUE TITLE
Bug with adding a region to some of  the "lieux" (places) in Signe Laval 

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#82] opened 2024-08-12 15:13 UTC
BUG: Sometimes the region (quartier) does not get added when it is selectd. Please see [this place as an example](https://cms.footlight.io/dashboard/63457978637093005071a053/places/64faeecda59a070066bbeb96)

I also downloaded the CSV file of all events (see below in comments)
That place has no data for region (columns AT and AV) The place is called Annexe3.

Note from Maude
I have this situation going on and it's not the first time (sorry i forgot to flag it the other time aroud). 
The quartier was entered bu then it's not there...  
![Image](https://github.com/user-attachments/assets/9073955e-2cad-4e74-bc21-f8af8f721d06)
(and all the event in location that are not in laval are not in the calendar in the front end so if you could check that all the quartier are truly there in all the lieux that would be great.

**Comment by troughc** [comment] 2024-08-12 16:10
@MaudeFJ can you please share the footlight CMS link for this place (the one in your screenshot)?

**Comment by MaudeFJ** [comment] 2024-08-12 16:14
https://cms.footlight.io/dashboard/63457978637093005071a053/places/64faeecda59a070066bbeb96

**Comment by MaudeFJ** [comment] 2024-08-12 16:14
Do i need to let it uncorrected ?

**Comment by troughc** [comment] 2024-08-12 16:19
@MaudeFJ Yes, please leave it uncorrected so we can find the problem.

Also, I am attaching the spreadsheet with the regions. Look at columns AT and AV. Most seem to be there (not the one you mentioned). The ones that aren't there don't seem to have an ID either.
What is the quartier for the one you mentioned above?


[export-csv-file_Place-c79ac5d5-548e-4927-abd4-493746c2bfe8.csv](https://github.com/user-attachments/files/16589427/export-csv-file_Place-c79ac5d5-548e-4927-abd4-493746c2bfe8.csv)

**Comment by MaudeFJ** [comment] 2024-08-12 16:24
Laval des rapides

________________________________
De : troughc ***@***.***>
Envoyé : 12 août 2024 12:20
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Can we do a double check on all the "lieux" for the neighborhood ? (Issue #82)


@MaudeFJ<https://github.com/MaudeFJ> Yes, please leave it uncorrected so we can find the problem.

Also, I am attaching the spreadsheet with the regions. Look at columns AT and AV. Most seem to be there (not the one you mentioned). The ones that aren't there don't seem to have an ID either.
What is the quartier for the one you mentioned above?

export-csv-file_Place-c79ac5d5-548e-4927-abd4-493746c2bfe8.csv<https://github.com/user-attachments/files/16589427/export-csv-file_Place-c79ac5d5-548e-4927-abd4-493746c2bfe8.csv>

**Comment by MaudeFJ** [comment] 2024-08-12 16:35
Cant i fill in the document you send so that those without can be all updated at once ?
________________________________
De : troughc ***@***.***>
Envoyé : 12 août 2024 12:20
À : culturecreates/tech-support-tickets ***@***.***>
Cc : Maude Fraser ***@***.***>; Mention ***@***.***>
Objet : Re: [culturecreates/tech-support-tickets] Can we do a double check on all the "lieux" for the neighborhood ? (Issue #82)


@MaudeFJ<https://github.com/MaudeFJ> Yes, please leave it uncorrected so we can find the problem.

Also, I am attaching the spreadsheet with the regions. Look at columns AT and AV. Most seem to be there (not the one you mentioned). The ones that aren't there don't seem to have an ID either.
What is the quartier for the one you mentioned above?

export-csv-file_Place-c79ac5d5-548e-4927-abd4-493746c2bfe8.csv<https://github.com/user-attachments/files/16589427/export-csv-file_Place-c79ac5d5-548e-4927-abd4-493746c2bfe8.csv>

**Comment by troughc** [comment] 2024-08-12 16:53
@MaudeFJ yes absolutely, you can. Please send it back to me and I will update it. 
Before I do, I would also like to see if the team can figure out what is going wrong.

**Comment by troughc** [comment] 2024-08-13 16:38
[MAJ_CT-export-csv-file_Place-c79ac5d5-548e-4927-abd4-493746c2bfe8.csv](https://github.com/user-attachments/files/16602640/MAJ_CT-export-csv-file_Place-c79ac5d5-548e-4927-abd4-493746c2bfe8.csv)

@sahalali @dev-aravind the attached file was downloaded via swagger and then modified to update to add the region to some of the places. There is one row (one place named église Saint-Jean-Gualbert) that doesn't have the region ID data currently - the correct ID still needs to be added to column E. 

Before we upload, can you please investigate why some places do not properly save the region (see description at top)? Or reassign to the correct person to investigate.

**Comment by troughc** [comment] 2024-08-16 19:27
@dev-aravind @sahalali I uploaded the file via swagger as Maude needed it sooner than expected. So her problem is resolved. However, I don't know if you are able to investigate why it happens in the first place. Can you still check even though the database has been updated?
Thanks, see you Monday (night for you).

**Comment by suhail-aliyar** [comment] 2024-08-20 10:07
The problem was not able to be replicated. 
I tried adding, updating and removing regions. All worked as expected.
However, as region is mandatory, I could not remove region and test.

**Comment by troughc** [comment] 2024-08-20 12:11
@sahalali this issue happened with an event that was imported by the aggregator user acomotion. 
Here's an idea, I don't know if it will work. Lets try the following to see if we can reproduce it.
1. Create a 'fake' place that is imported by the acomotion aggregator user
2. try to add a region to that place. Try adding the 'laval des rapide' quartier and then save the place
3. Go back in and see if the region/quartier is displayed or blank. If it is blank then you have reproduced the error.

**Comment by suhail-aliyar** [comment] 2024-08-21 11:28
I still couldn't reproduce this issue. Let's schedule a working session today to figure out what's causing the problem.

**Comment by troughc** [comment] 2024-08-28 13:20
After further investigation, we were able to see that this is a legacy issue that was created in 2023. As a result, in specific cases, when a taxonomy term is deleted, this problem can arise.
We reviewed the database and don't expect it to happen again. However,  @MaudeFJ, if you do see this again, please let us know.

**Closed as completed** 2024-08-28 13:21 UTC
Labels: Signé Laval, bug
