### ISSUE TITLE
Bug filters

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#105] opened 2024-12-12 17:46 UTC
I selected brouillon, then selected the user  avilledelaval, but the brouillon from other users are still there... 
![Capture d’écran, le 2024-12-12 à 12 44 30](https://github.com/user-attachments/assets/3300bbc8-96eb-436e-b3ad-f105174e6220)

**Comment by AbhishekPAnil** [comment] 2024-12-16 05:49
This has been fixed with the above PR .
Tested in production:PASSED.

**Closed as completed** 2024-12-16 05:49 UTC

**Comment by troughc** [comment] 2024-12-16 13:57
@MaudeFJ this was a side effect bug that was caused by another issue we were working on. It's fixed now. Have a great day!
