### ISSUE TITLE
Question : When are the event from the community are being uploaded in arts data ?

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#93] opened 2024-10-02 18:58 UTC
We are working on a partner ship with la vitrine and its relying in the fact that our events are shared in the graph, and I see lots of events without the little link. I'm then wondering whats the frequency of this upload. 
Thank you !

**Comment by MaudeFJ** [comment] 2024-10-02 19:32
I'm also trying to see my events in arts data and I can't find them... 
https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Fartsdata-planet-footlight%2Fsigne-laval-cms-events

**Comment by troughc** [comment] 2024-10-02 21:10
@saumier could you please take a look at this? Maude also message this:
I'm also trying to see my events in arts data and I can't find them...
https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Fartsdata-planet-footlight%2Fsigne-laval-cms-events

**Comment by saumier** [comment] 2024-10-03 12:39
@MaudeFJ @troughc The events from Signé Laval are loaded into Artsdata. You can view them on Artsdata by looking at the list of data feeds. here https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20signe-laval&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/signe-laval

There is a limitation with CMS today: CMS does not export the sub-events for event series, only the top level event. This is good for expositions, since LaVitrine does not want each day of the week. However, for performances by the same artists that are grouped into a single Event series, this is not good. The export of event series sub-events is not yet scheduled in the road map of Footlight CMS.

You can see the data being sent to LaVitrine including Singé-Laval's CMS events here https://github.com/culturecreates/artsdata-planet-lavitrine?tab=readme-ov-file

**Comment by MaudeFJ** [comment] 2024-10-03 12:54
> @saumier could you please take a look at this? Maude also message this: I'm also trying to see my events in arts data and I can't find them... https://artsdata-nebula-d1ec887e2637.herokuapp.com/entity?uri=http%3A%2F%2Fkg.artsdata.ca%2Fculture-creates%2Fartsdata-planet-footlight%2Fsigne-laval-cms-events

I found them that's why I deleted it ! thanks

**Comment by MaudeFJ** [comment] 2024-10-03 13:02
Regarding the event in arts data, 
For exemple i see terre d'accueil in there : https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Flod.footlight.io%2Fresource%2F667839ad1180fb0064613680 
But there is no link icon in the cms... 
<img width="896" alt="Capture d’écran, le 2024-10-03 à 08 56 40" src="https://github.com/user-attachments/assets/8f05541c-cc2c-45fe-bdaa-b2174cf84f53">


Also in there is this only upcoming events ? https://kg.artsdata.ca/en/query/show?title=Event%20entities%20in%20signe-laval&sparql=list_events&graph=http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/signe-laval

And my question is what is the frequency of the upload, every mardi like the other way around ? 

For the event series, that mean every event that as multiple date ? 

Thanks !

**Comment by troughc** [comment] 2024-10-03 16:20
@MaudeFJ to answer your questions:

1. You see terre d'accueil in there : https://kg.artsdata.ca/en/entity?uri=http%3A%2F%2Flod.footlight.io%2Fresource%2F667839ad1180fb0064613680
**But there is no link icon in the cms**

**Answer:** this is because this event is not 'minted' in Artsdata (i.e. an Artsdata unique identifier had not been created for it). 
<img width="1264" alt="Screenshot 2024-10-03 at 12 08 05 PM" src="https://github.com/user-attachments/assets/37377936-6306-454e-bece-588be3f0a5d2">
Sometime after this event gets minted, you will see a link icon in the CMS. Minting is an ongoing activity in Artsdata (and known to the Artsdata community group). Extending automatic minting is in progress. 

2. Also in there is this only upcoming events (in Artsdata) ? 
**Answer:** Yes, that is correct. The Artsdata community group should be aware as we have not set up an official archive process or allocated work to this activity. **@saumier please feel free to add any salient details.** 

3. ...what is the frequency of the upload (to Artsdata), is it every mardi like the other way around ? 
**Pending Answer:**  I am not exactly sure but I think it is much more often than that...**@saumier can you answer this question?**

4. For the event series, that mean every event that (has) multiple dates ? 
**Answer:**  Yes, event series, meaning multiple dates with multiple sub events (as opposed to a single date event or a date range event). What happens TODAY with multiple date events (events with sub-events): multiple date events that come from the Footlight CMS are loaded into Artsdata as DATE RANGE events. In other words, the multiple date event with sub-events becomes a single event that has a start date (the first date of the first sub-event) and end date (the date of the last sub-event). **@saumier please feel free to add any salient details.**

**Comment by saumier** [comment] 2024-10-04 13:01
@MaudeFJ @troughc A couple of additional points:
1. Today the events sent to LaVitrine do not require Artsdata IDs. So events in Singé Laval are sent to LaVitrine even if they don't have an Artsdata ID. If there is a duplicate event from another website, like co-motion and signé Laval, then LaVitrine will receive duplicates. They handle the duplicates at their end. In the example, LaVitrine can check the sameAs because co-motion has Artsdata IDs and events in Signé Laval from co-motion will have the same Artsdata ID. 
2. Event series with `Multiple dates/plusieurs dates` are sent to LaVitrine. For example: [Dimanches Aéro](https://cms.footlight.io/dashboard/63457978637093005071a053/events/66c38c5ad09b4d006355dbc4) is sent to LaVitrine with the startDate and endDate **BUT not the individual sub-events**
3. The events are saved to a 'dump' file daily on the Artsdata Databus (sort of like Données Quebec). Only upcoming events are saved in the 'dump' file. I don't know the procedure at LaVitrine but I think they load the 'dump' daily.
4. I looked at "Québec, terre d'accueil" and it should be sent to LaVitrine without needed an Artsdata ID. However it is not in the [dump](https://api.artsdata.ca/databus/artifact/latest?artifact=http%3A%2F%2Fkg.artsdata.ca%2Fdatabus%2Fculture-creates%2Fartsdata-planet-lavitrine%2Fsigne-laval-cms-events) I checked today. I'll look into this to understand why.

**Comment by troughc** [comment] 2024-10-07 14:22
@saumier regarding: I looked at "Québec, terre d'accueil" and it should be sent to LaVitrine without needed an Artsdata ID. However it is not in the [dump](https://api.artsdata.ca/databus/artifact/latest?artifact=http%3A%2F%2Fkg.artsdata.ca%2Fdatabus%2Fculture-creates%2Fartsdata-planet-lavitrine%2Fsigne-laval-cms-events) I checked today. I'll look into this to understand why.
What was the outcome of this?

**Comment by troughc** [comment] 2024-10-07 14:23
@MaudeF Have all of your concerns have been addressed? thanks.

**Comment by MaudeFJ** [comment] 2024-10-07 14:31
I went to la vitrine last week and a lot of event from signé Laval were not there, that why I was wondering. So I don't think the problem is only with Terre d'accueil..

**Comment by troughc** [comment] 2024-10-07 15:35
> I went to la vitrine last week and a lot of event from signé Laval were not there, that why I was wondering. So I don't think the problem is only with Terre d'accueil..

@saumier FYI

**Comment by troughc** [comment] 2024-10-07 17:31
@MaudeFJ I spoke with @saumier and he has logged this problem in another issue to specifically address and solve it. 
The problem is that events without times (dates without an heure) are not getting through to La Vitrine. This will be fixed in https://github.com/culturecreates/artsdata-planet-lavitrine/issues/38.

Regarding how often your events (Signe Laval) are uploaded to Artsdata - they are uploaded weekly on Wednesdays (at 1AM). 

I will now close this issue.

**Closed as completed by troughc** 2024-10-07 17:31 UTC
