### ISSUE TITLE
Bug : error message - unable to open event

### ISSUE THREAD

**Issue by MaudeFJ** [culturecreates/tech-support-tickets#70] opened 2024-06-18 19:04 UTC
<img width="1722" alt="Capture d’écran, le 2024-06-18 à 15 01 57" src="https://github.com/culturecreates/tech-support-tickets/assets/135066077/170eca90-01e4-4d83-974f-c45e686b309a">
i published this event and its broken on the website https://signelaval.com/fr/evenements/6669113d92cafd006497401c/bibliomobile-et-contes-mobiles-au-parc-rodolphe-lavoie
And i have and error message in the CMS.

**Comment by troughc** [comment] 2024-06-18 20:33
@AbhishekPAnil I can confirm this is happening for me with this event: https://cms.footlight.io/dashboard/63457978637093005071a053/events/add-event/6669113d92cafd006497401c

cc @saumier

**Comment by dev-aravind** [comment] 2024-06-19 09:43
@troughc This bug was caused by events having no images having their image property set as null. A fix has been deployed in the backend. 

@AbhishekPAnil Can you update the front end side such that if there are no images for an event, it is saved as an empty array? Thanks.

**Comment by AbhishekPAnil** [comment] 2024-06-19 10:10
While removing the main image ,previously we used to set the image as a null a value.Since the image is now an array ,we don't need to pass a null value instead we can pass an empty array.This will be dealt in this issue https://github.com/culturecreates/footlight-app/issues/1165.This is just a code refactoring in the frontend and this doesn't affect the events directly .

**Comment by troughc** [comment] 2024-06-19 12:10
@MaudeFJ this event is now back and loading in the CMS.

**Closed as completed** 2024-06-19 12:10 UTC
Labels: bug
